### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by TurtleWolfe** [TurtleWolfe/tmx#13]
- [ ] **`search bar`**
###
- [ ] **`header`** title, primary.main
- [ ] responsive **`header`** (hamburger menu)
###
- [ ] action card in **`Image List`**
- [ ] isolate reactions per **`image Card`**
- [ ] title color primary.main in **`ListItemBar`**
### 
- [ ] **`details`** page (from `Map` and `FaveList `components)
- [ ] **`permission`**  to center from **`Lat`** & **`Long`** location **`?`**
- [ ] [Snazzy Maps](https://snazzymaps.com/style/8097/wy "Gray Scale Styling")
